language: node_js
node_js:
  - "node"
script:
# fix for https://github.com/npm/npm/issues/6246:
  - npm -g install npm
  - npm --version
  - npm install
  - npm run coveralls
  - npm run lint
  - npm run generate-docs
